"""
sanitizer.py
-------------
Provides a best-effort JavaScript sanitizer to prevent
potentially unsafe operations in generated code.

It does NOT make execution fully secure — it just blocks
obvious network or evaluation functions such as:
- fetch()
- XMLHttpRequest
- WebSocket
- navigator.sendBeacon()
- import()
- eval()

For untrusted or public use, run generated code inside an
isolated sandbox or container instead.
"""

import re


def sanitize_js(js: str) -> str:
    """
    Sanitize JavaScript by replacing dangerous patterns with comments.

    Args:
        js (str): JavaScript source code generated by the model.

    Returns:
        str: A sanitized version safe to run locally.
    """
    if not js:
        return js or ""

    # List of dangerous patterns (case-insensitive)
    patterns = [
        (r"fetch\s*\(", "/* fetch blocked */("),
        (r"new\s+WebSocket\s*\(", "/* WebSocket blocked */("),
        (r"XMLHttpRequest", "/* XMLHttpRequest blocked */"),
        (r"navigator\.sendBeacon\s*\(", "/* sendBeacon blocked */("),
        (r"\bimport\s*\(", "/* dynamic import blocked */("),
        (r"\beval\s*\(", "/* eval blocked */("),
        (r"Function\s*\(", "/* Function constructor blocked */(")
    ]

    sanitized = js
    for pattern, replacement in patterns:
        sanitized = re.sub(pattern, replacement, sanitized, flags=re.IGNORECASE)

    # Optional: truncate extremely long single lines (>2000 chars)
    sanitized = "\n".join(
        (line if len(line) <= 2000 else line[:2000] + " /* truncated line */")
        for line in sanitized.splitlines()
    )

    return sanitized
